// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';

export function GenerateAudio(arg1:ai.AudioRequest):Promise<ai.AIResponse>;

export function GenerateImage(arg1:ai.ImageRequest):Promise<ai.AIResponse>;

export function GenerateText(arg1:ai.TextRequest):Promise<ai.AIResponse>;

export function GenerateVideo(arg1:ai.VideoRequest):Promise<ai.AIResponse>;
