// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAudio(arg1) {
  return window['go']['ai']['Service']['GenerateAudio'](arg1);
}

export function GenerateImage(arg1) {
  return window['go']['ai']['Service']['GenerateImage'](arg1);
}

export function GenerateText(arg1) {
  return window['go']['ai']['Service']['GenerateText'](arg1);
}

export function GenerateVideo(arg1) {
  return window['go']['ai']['Service']['GenerateVideo'](arg1);
}
