// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';

export function CanvasAgent(arg1:ai.CanvasAgentRequest):Promise<void>;

export function GenerateAudio(arg1:ai.AudioRequest):Promise<ai.AIResponse>;

export function GenerateImage(arg1:ai.ImageRequest):Promise<ai.AIResponse>;

export function GenerateText(arg1:ai.TextRequest):Promise<ai.AIResponse>;

export function GenerateVideo(arg1:ai.VideoRequest):Promise<ai.AIResponse>;

export function ListModels(arg1:any):Promise<Array<ai.Model>>;

export function UpdateCanvasState(arg1:string,arg2:Array<Record<string, any>>,arg3:Array<Record<string, any>>):Promise<void>;
