// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteModelProvider(arg1) {
  return window['go']['database']['Service']['DeleteModelProvider'](arg1);
}

export function GetModelProvider(arg1) {
  return window['go']['database']['Service']['GetModelProvider'](arg1);
}

export function ListModelProviders() {
  return window['go']['database']['Service']['ListModelProviders']();
}

export function SaveModelProvider(arg1) {
  return window['go']['database']['Service']['SaveModelProvider'](arg1);
}
