// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function DeleteAIConfig(arg1:string):Promise<void>;

export function GetAIConfig(arg1:string):Promise<database.AIConfig>;

export function ListAIConfigs():Promise<Array<database.AIConfig>>;

export function SaveAIConfig(arg1:database.AIConfig):Promise<void>;
