// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAsset(arg1) {
  return window['go']['database']['Service']['DeleteAsset'](arg1);
}

export function DeleteModelProvider(arg1) {
  return window['go']['database']['Service']['DeleteModelProvider'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['database']['Service']['DeleteProject'](arg1);
}

export function GetModelProvider(arg1) {
  return window['go']['database']['Service']['GetModelProvider'](arg1);
}

export function GetProject(arg1) {
  return window['go']['database']['Service']['GetProject'](arg1);
}

export function ListAssets(arg1) {
  return window['go']['database']['Service']['ListAssets'](arg1);
}

export function ListModelProviders() {
  return window['go']['database']['Service']['ListModelProviders']();
}

export function ListProjects() {
  return window['go']['database']['Service']['ListProjects']();
}

export function SaveModelProvider(arg1) {
  return window['go']['database']['Service']['SaveModelProvider'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['database']['Service']['SaveProject'](arg1);
}
