// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function DeleteModelProvider(arg1:number):Promise<void>;

export function GetModelProvider(arg1:number):Promise<database.ModelProvider>;

export function ListModelProviders():Promise<Array<database.ModelProvider>>;

export function SaveModelProvider(arg1:database.ModelProvider):Promise<void>;
