// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function CreateAssetFromFile(arg1:string,arg2:Array<number>):Promise<database.Asset>;

export function DeleteAsset(arg1:number):Promise<void>;

export function DeleteModelProvider(arg1:number):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetModelProvider(arg1:number):Promise<database.ModelProvider>;

export function GetProject(arg1:number):Promise<database.Project>;

export function ListAssets(arg1:number):Promise<Array<database.Asset>>;

export function ListModelProviders():Promise<Array<database.ModelProvider>>;

export function ListProjects():Promise<Array<database.Project>>;

export function SaveModelProvider(arg1:database.ModelProvider):Promise<void>;

export function SaveProject(arg1:database.Project):Promise<database.Project>;
