// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAIConfig(arg1) {
  return window['go']['database']['Service']['DeleteAIConfig'](arg1);
}

export function GetAIConfig(arg1) {
  return window['go']['database']['Service']['GetAIConfig'](arg1);
}

export function ListAIConfigs() {
  return window['go']['database']['Service']['ListAIConfigs']();
}

export function SaveAIConfig(arg1) {
  return window['go']['database']['Service']['SaveAIConfig'](arg1);
}
