// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['app']['Service']['CheckUpdate']();
}

export function GetWailsJSON() {
  return window['go']['app']['Service']['GetWailsJSON']();
}
