// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CheckUpdate():Promise<app.UpdateInfo>;

export function GetWailsJSON():Promise<string>;
