// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function BackupData():Promise<void>;

export function CheckUpdate():Promise<app.UpdateInfo>;

export function GetInitError():Promise<string>;

export function GetUserPreference(arg1:string):Promise<string>;

export function GetWailsJSON():Promise<string>;

export function ResetDatabase():Promise<void>;

export function SetUserPreference(arg1:string,arg2:string):Promise<void>;
